---

- name: Configure /etc/ files
  become: true
  vars:
    __system_bashrc_filename: "{{ 'bash.bashrc' if ansible_distribution_file_variety | lower == 'debian' else 'bashrc' }}"
  block:
    - name: 🐜 Distribution file variety is
      debug:
        var: ansible_distribution_file_variety
        verbosity: 1

    - name: Bash | Configure bashrc files
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/bash/bashrc.yml"

    - name: Bash | Configure profile files
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/bash/profile.yml"

    - name: Bash | Configure shell environment
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/bash/env.yml"

