---
# Configure low-level system services

- name: Configure NTP service
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/services/ntp.yml"

- name: Configure SSH service
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/services/sshd.yml"

