---
# Configure low-level system services

- name: Configure NTP service
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/services/ntp.yml"

- name: Configure SSH service
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/services/sshd.yml"

- name: Configure cron service
  when: system_enable_cron
  become: true
  ansible.builtin.systemd_service:
    name: crond
    enabled: true
    state: started

