---

# Set the timezone to Etc/UTC
- name: Configure system timezone
  become: true
  block:
    - name: Check if timezone is already set
      ansible.builtin.debug:
        msg: "The timezone is already set to {{ system_timezone }}."
      when: ansible_date_time.tz == system_timezone

    - name: Set timezone to {{ system_timezone }}
      community.general.timezone:
        name: "{{ system_timezone }}"
      register: timezone_change
      when: ansible_date_time.tz != system_timezone

