---
role_name_check: 0
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
platforms:
  - name: role-system-ec2-rocky10
    type: ec2
    image: ami-0efe0bc32b69b2efe    # Rocky Linux 10 (Official) - x86_64
    region: us-east-2
    instance_type: t3.small
    ssh_user: molecule_runner
    vpc_id: vpc-0eb9fd1391f4207ec
    vpc_subnet_id: subnet-0aa189c0d6fc53923
    boot_wait_seconds: 5
    hostvars:
      org: molecule
      env: ci
  - name: role-system-ec2-rocky9arm
    type: ec2
    image: ami-08dc10d7a4f808a53    # Rocky Linux 9 (Official) - aarch64
    region: us-east-2
    instance_type: t4g.micro
    ssh_user: molecule_runner
    vpc_id: vpc-0eb9fd1391f4207ec
    vpc_subnet_id: subnet-0aa189c0d6fc53923
    boot_wait_seconds: 5
    hostvars:
      org: molecule
      env: ci
      # Test legacy system-wide pip package installation
      system_enable_pip_packages: true
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../resources/create.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    side_effect: ../resources/side_effect.yml
    verify: ../resources/verify.yml
    cleanup: ../resources/cleanup.yml
    destroy: ../resources/destroy.yml
  config_options:
    defaults:
      gathering: explicit
      playbook_vars_root: top
      verbosity: ${ANSIBLE_VERBOSITY:-0}
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
  enabled: true

