---
# The side effect playbook executes actions which produce side effects to the instances(s). Intended to test HA failover scenarios or the like.

- name: Test role execution with only MOTD feature enabled
  hosts: molecule
  tasks:
    - name: Load test configuration
      tags: always
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/vars/main.yml"

    - name: Run system role with only MOTD enabled
      vars:
        ansible_user: molecule_runner
        system_motd_config_version: molecule-ci-test
        system_default: false
        system_enable_motd: true
      ansible.builtin.include_role:
        name: system

    - name: Verify execution state
      ansible.builtin.assert:
        that:
          - system_ntp_configured is not defined
        fail_msg: >
          NTP configuration should not run with only MOTD feature enabled! Something went wrong!
        success_msg: "NTP configuration is disabled as expected!"

- name: Test package removal from virtual environment
  hosts: molecule
  tasks:
    - name: Load test configuration
      tags: always
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/vars/main.yml"

    - name: Run system role with venv package removal
      vars:
        ansible_user: molecule_runner
        system_default: false
        system_enable_venv: true
        system_venv_packages_remove:
          - pytz
      ansible.builtin.include_role:
        name: system

