---
# Verify that the role being tested has done what it's supposed to

- name: Verify
  hosts: molecule
  vars:
    ansible_user: molecule_runner
  tasks:
    - name: Load test configuration
      tags: always
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/vars/main.yml"

    - name: Load system facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - distribution

    - name: Add compatibility options for legacy OS
      when: >-
        ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2' or
        ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
      ansible.builtin.set_fact:
        ## This is set here because AL2 doesn't support the default values which use the Include directive
        system_sshd_config_defaults:
          AuthorizedKeysFile: .ssh/authorized_keys
        ansible_python_interpreter: /usr/local/bin/python3.10

    - name: Verify environment variables
      block:
        - name: Load user env var
          ansible.builtin.command:
            cmd: bash -i -c "echo $I_AM_ROBOT"
          changed_when: false
          register: __ci_user_env_var

        - name: Load system env var
          ansible.builtin.command:
            cmd: bash -i -c "echo $TZ"
          changed_when: false
          register: __ci_system_env_var

        - name: Validate env vars
          ansible.builtin.assert:
            that:
              - __ci_user_env_var.stdout | trim == "true"
              - __ci_system_env_var.stdout | trim == "UTC"
            fail_msg: "Environment variables are not set as expected!"
            success_msg: "Environment variables are set as expected."

    - name: Validate setting path works
      block:
        - name: Attempt to run PATH test script in a login shell
          ansible.builtin.shell:
            cmd: bash -l path_test.sh
          register: __ci_path_test
          changed_when: false

        - name: Validate PATH test script output
          ansible.builtin.assert:
            that:
              - __ci_path_test.stdout == "Durp!"
            fail_msg: "PATH test script did not output as expected! Output: {{ __ci_path_test.stdout }}"
            success_msg: "PATH test script output is as expected!"

    - name: Verify Python virtual environment
      ansible.builtin.include_tasks:
        file: tasks/verify-venv.yml
