---
# Verify that the role being tested has done what it's supposed to

- name: Verify
  hosts: molecule
  tasks:
    - name: Load system facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - distribution

    - name: Add compatibility options for legacy OS
      when: >-
        ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2' or
        ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
      ansible.builtin.set_fact:
        ## This is set here because AL2 doesn't support the default values which use the Include directive
        system_sshd_config_defaults:
          AuthorizedKeysFile: .ssh/authorized_keys
        ansible_python_interpreter: /usr/local/bin/python3.10

    - name: Run system role with only MOTD enabled
      ansible.builtin.include_role:
        name: system
      vars:
        ansible_user: molecule_runner
        system_motd_config_version: molecule-ci-test
        system_default_enable: false
        system_enable_motd: true

    - name: Verify execution state
      ansible.builtin.assert:
        that:
          - system_ntp_configured is not defined
        fail_msg: "NTP configuration should not be enabled! Something went wrong!"
        success_msg: "NTP configuration is disabled as expected!"

    - name: Validate setting path works
      block:
        - name: Attempt to run PATH test script in a login shell
          ansible.builtin.shell:
            cmd: bash -l path_test.sh
          register: __ci_path_test
          changed_when: false

        - name: Validate PATH test script output
          ansible.builtin.assert:
            that:
              - __ci_path_test.stdout == "Durp!"
            fail_msg: "PATH test script did not output as expected! Output: {{ __ci_path_test.stdout }}"
            success_msg: "PATH test script output is as expected!"

    - name: Run system role with default settings
      ansible.builtin.include_role:
        name: system

