---
# handlers file for System

## Service handlers
- name: Reload systemd service files
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart resolved service
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart journald service
  become: true
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Restart sshd service
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

## NTP handlers
- name: Restart chronyd
  become: true
  ansible.builtin.service:
    name: chronyd
    state: restarted

