---
role_name_check: 0
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
    login_cmd_template: 'docker exec -ti {instance} bash --login'
platforms:
  - name: role-system-fedora42
    type: docker
    image: geerlingguy/docker-fedora42-ansible:latest
    systemd: True
    modify_image: False
    privileged: True
    hostvars:
      system_packages_auto_update_category: default   # Fedora doesn't include errata in repos
      system_bash_disable_color_prompt: true  # Ensure color prompt logic works with this option
      ci_custom_python_interpreter: /opt/ansible-venv/bin/python  # Test with venv interpreter

  - name: role-system-rocky9
    type: docker
    image: geerlingguy/docker-rockylinux9-ansible:latest
    systemd: True
    modify_image: False
    privileged: True
    hostvars: {}

  - name: role-system-ubuntu2204
    type: docker
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    systemd: True
    modify_image: False
    privileged: True
    hostvars:
      system_packages_auto_update_category: default   # Ubuntu doesn't include errata in repos
      system_enable_packages_auto_update: false   # Ubuntu is not yet supported
      system_bash_prompt_symbols: {}      # Test with no prompt symbols
      system_bash_color_prompt_symbols: {} # Test with no prompt symbols
      system_venv_set_interpreter: true  # Test with python interpreter override
      system_venv_package_state: latest  # Test with latest package state
      system_venv_packages_extra:
        - "boto3==1.40.55"
        - docker

  - name: role-system-ubuntu2404
    type: docker
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    systemd: True
    modify_image: False
    privileged: True
    hostvars:
      system_packages_auto_update_category: default   # Ubuntu doesn't include errata in repos
      system_enable_packages_auto_update: false   # Ubuntu is not yet supported
      system_enable_pip_packages: false   # Deprecated - using venv instead
      system_enable_venv: true   # Use venv for Python packages (modern approach)
      system_venv_packages_state: present  # Test with present package state

  - name: role-system-amazon2023
    type: docker
    image: geerlingguy/docker-amazonlinux2023-ansible:latest
    systemd: True
    modify_image: False
    privileged: True
    hostvars:
      # Test color prompt aliases
      system_bash_coloraliases:
        ls: "ls --color=auto"
        dir: "dir --color=auto"
        vdir: "vdir --color=auto"
        grep: "grep --color=auto"
        fgrep: "fgrep --color=auto"
        egrep: "egrep --color=auto"
      system_enable_pip_packages: false   # Deprecated - using venv instead
      system_enable_venv: true   # Use venv for Python packages (modern approach)
provisioner:
  name: ansible
  log: True
  inventory:
    group_vars:
      molecule:
        org: molecule
        env: ci
        system_enable_hostname: false   # Can't replace hostname file in docker containers
  playbooks:
    create: ../resources/create.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    side_effect: ../resources/side_effect.yml
    verify: ../resources/verify.yml
    cleanup: ../resources/cleanup.yml
    destroy: ../resources/destroy.yml
  config_options:
    defaults:
      gathering: explicit
      playbook_vars_root: top
      verbosity: ${ANSIBLE_VERBOSITY:-0}
  env:
    ANSIBLE_ROLES_PATH: /usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles:${PWD}/roles:${PWD}/../roles:${PWD}/../../roles
    ANSIBLE_COLLECTIONS_PATH: /usr/share/ansible/collections:~/.ansible/collections:${PWD}/collections:${PWD}/../collections:${PWD}/../../collections
    ARA_API_CLIENT: ${ARA_API_CLIENT:-'http'}
    ARA_API_SERVER: ${ARA_API_SERVER:-'http://localhost:8000'}
    ARA_DEFAULT_LABELS: ${ARA_DEFAULT_LABELS:-'testing,molecule'}
    # To use Ara with molecule:
    #  export the ANSIBLE_CALLBACK_PLUGINS env var with the output of 'python3 -m ara.setup.callback_plugins'
    ANSIBLE_CALLBACK_PLUGINS: ${ANSIBLE_CALLBACK_PLUGINS}
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
  enabled: true

