---

name: Deploy Role
on:
  release:
    types:
      - created
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.release.prerelase == false
    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy Role
        uses: buluma/galaxy-action@v10.30.23
        with:
          galaxy_api_key: '${{ secrets.GALAXY_API_KEY }}'

