---

name: Role - system
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/role-system.yml'
      - './**'
      - '!*.md'
    schedule:
      - cron: '13 13 * * *'

jobs:
  manage-system:
    name: "Role: system"
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        molecule-scenario:
          - role-system-docker

    if: >
      (github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref_name == 'main'))
    uses: ./.github/workflows/_run-molecule-test.yml
    with:
      scenario: ${{ matrix.molecule-scenario }}
      python-version: ${{ matrix.python-version }}
      python-dependencies: boto3
    secrets: inherit

